# Generated by Django 3.2.13 on 2022-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.TextField(max_length=200, null=True)),
                ('Comments', models.TextField(max_length=200, null=True)),
                ('Reg_no', models.TextField(max_length=200, null=True)),
                ('DT', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'customer_comments',
                'ordering': ['DT'],
            },
        ),
        migrations.CreateModel(
            name='RY_Enquiry_Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_no', models.TextField(max_length=200, null=True)),
                ('Mill', models.TextField(max_length=200, null=True)),
                ('Mill_Rep', models.TextField(max_length=200, null=True)),
                ('Customer', models.TextField(max_length=200, null=True)),
                ('Marketing_Zone', models.TextField(max_length=200, null=True)),
                ('Payment_Term', models.TextField(max_length=200, null=True)),
                ('Narration', models.TextField(max_length=200, null=True)),
                ('Reason_For_Non_Acception', models.TextField(max_length=200, null=True)),
                ('Replied_From_the_mill', models.TextField(max_length=200, null=True)),
                ('Acceptance_from_the_mill', models.TextField(max_length=200, null=True)),
                ('Date', models.TextField(max_length=200, null=True)),
                ('Email_Details', models.TextField(max_length=200, null=True)),
                ('Status', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'RY_Enquiry_Header',
                'ordering': ['Reg_no'],
            },
        ),
        migrations.CreateModel(
            name='RY_Enquiry_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counts', models.TextField(max_length=200, null=True)),
                ('Quality', models.TextField(max_length=200, null=True)),
                ('Type', models.TextField(max_length=200, null=True)),
                ('Blend', models.TextField(max_length=200, null=True)),
                ('Shade', models.TextField(max_length=200, null=True)),
                ('Shade_Ref', models.TextField(max_length=200, null=True)),
                ('Depth', models.TextField(max_length=200, null=True)),
                ('UOM', models.TextField(max_length=200, null=True)),
                ('Quantity', models.TextField(max_length=200, null=True)),
                ('Status', models.TextField(max_length=200, null=True)),
                ('Reg_no', models.TextField(max_length=200, null=True)),
                ('Supplier_Rate', models.ImageField(max_length=200, null=True, upload_to='')),
                ('Supplier_Amount', models.ImageField(max_length=200, null=True, upload_to='')),
                ('Supplier_Last_order', models.TextField(max_length=200, null=True)),
                ('Agent_Rate', models.ImageField(max_length=200, null=True, upload_to='')),
                ('Agent_Amount', models.ImageField(max_length=200, null=True, upload_to='')),
                ('Agent_Last_order', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'RY_Enquiry_Items',
                'ordering': ['Reg_no'],
            },
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.TextField(max_length=200, null=True)),
                ('Password', models.TextField(max_length=200, null=True)),
                ('Role', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'User_Details',
                'ordering': ['Role'],
            },
        ),
    ]
