# Generated by Django 4.0.2 on 2022-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='CreatedByUser',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='LastUpdateby',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='LastUpdateddate',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='CreatedByUser',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='LastUpdateby',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='LastUpdateddate',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
