# Generated by Django 4.0.5 on 2022-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ry_enquiry_header',
            options={'ordering': ['Reg_no']},
        ),
        migrations.AlterModelOptions(
            name='ry_enquiry_items',
            options={'ordering': ['Reg_no']},
        ),
        migrations.RemoveField(
            model_name='ry_enquiry_header',
            name='Id',
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Mill_Rep',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='Amount',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='Last_order',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_items',
            name='Rate',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Acceptance_from_the_mill',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Customer',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Date',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Email_Details',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Marketing_Zone',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Mill',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Narration',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Payment_Term',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Reason_For_Non_Acception',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Reg_no',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_header',
            name='Replied_From_the_mill',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Blend',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Counts',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Depth',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Id',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Quality',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Quantity',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Reg_no',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Shade',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Shade_Ref',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Status',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Type',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='UOM',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='ry_enquiry_header',
            table='RY_Enquiry_Header',
        ),
        migrations.AlterModelTable(
            name='ry_enquiry_items',
            table='RY_Enquiry_Items',
        ),
    ]
