# Generated by Django 4.0.2 on 2022-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Delivery_Date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Ready_stock',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
