# Generated by Django 4.0.2 on 2022-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ry_enquiry_header',
            name='Cop_No',
        ),
        migrations.RemoveField(
            model_name='ry_enquiry_header',
            name='Pc_No',
        ),
        migrations.RemoveField(
            model_name='ry_enquiry_header',
            name='Sc_No',
        ),
        migrations.AlterField(
            model_name='customer_comments',
            name='Created_Date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
