# Generated by Django 4.1 on 2022-08-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Cop_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Pc_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ry_enquiry_header',
            name='Sc_Number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
