# Generated by Django 4.0.2 on 2022-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch_excel_dump',
            name='Data_RowIndex',
            field=models.IntegerField(max_length=2, null=True),
        ),
    ]
