# Generated by Django 4.0.2 on 2022-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0002_ry_enquiry_header_createdbyuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pono', models.CharField(max_length=200, null=True)),
                ('popdf', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'purchase_details',
            },
        ),
    ]
