# Generated by Django 4.0.2 on 2022-08-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0002_dispatch_excel_dump_data_rowindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_names', models.TextField(max_length=200, null=True)),
                ('customer_emailid', models.TextField(max_length=200, null=True)),
                ('splited_details', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Customer_Name',
            },
        ),
        migrations.CreateModel(
            name='Duplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Count', models.TextField(max_length=200, null=True)),
                ('Blend', models.TextField(max_length=200, null=True)),
                ('Shade_Ref', models.TextField(max_length=200, null=True)),
                ('Quantity', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Duplication',
            },
        ),
        migrations.CreateModel(
            name='items_to_mill_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=200, null=True)),
                ('mill', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'items_to_mill_mapping',
            },
        ),
        migrations.CreateModel(
            name='ShadeRef_With_mill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shade_ref', models.TextField(max_length=200, null=True)),
                ('shade', models.TextField(max_length=200, null=True)),
                ('type', models.TextField(max_length=200, null=True)),
                ('mill', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'ShadeRef_With_mill',
            },
        ),
        migrations.AlterField(
            model_name='email_distribution_groups',
            name='GroupUsersID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email_distribution_groups',
            name='Status',
            field=models.BooleanField(max_length=10, null=True),
        ),
    ]
