# Generated by Django 4.0.4 on 2022-06-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0002_user_details_alter_ry_enquiry_header_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='UseName',
            new_name='UserName',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
