# Generated by Django 4.0.2 on 2022-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0002_ry_enquiry_header_po_revdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_Schedule', models.CharField(max_length=100, null=True)),
                ('payment_term', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('matching_source', models.CharField(max_length=100, null=True)),
                ('buyer', models.CharField(max_length=100, null=True)),
                ('any_other_specification', models.CharField(max_length=100, null=True)),
                ('specification_if_no_product_type', models.CharField(max_length=100, null=True)),
                ('commision', models.CharField(max_length=100, null=True)),
                ('Baby_cone', models.BooleanField(max_length=10, null=True)),
                ('air', models.BooleanField(max_length=10, null=True)),
                ('Reg_no', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Other_Details',
            },
        ),
        migrations.CreateModel(
            name='Quantity_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feeder_stripes', models.CharField(max_length=100, null=True)),
                ('jacaquard', models.CharField(max_length=100, null=True)),
                ('mini_jaq', models.CharField(max_length=10, null=True)),
                ('auto_stripes', models.CharField(max_length=100, null=True)),
                ('single_jersey', models.CharField(max_length=100, null=True)),
                ('p_k', models.CharField(max_length=10, null=True)),
                ('interlock', models.CharField(max_length=100, null=True)),
                ('rib', models.CharField(max_length=100, null=True)),
                ('white', models.CharField(max_length=10, null=True)),
                ('light', models.CharField(max_length=100, null=True)),
                ('medium', models.CharField(max_length=100, null=True)),
                ('dark', models.CharField(max_length=10, null=True)),
                ('pay_mode', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(max_length=100, null=True)),
                ('bank', models.CharField(max_length=100, null=True)),
                ('Reg_no', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Quantity_Details',
            },
        ),
    ]
