# Generated by Django 4.0.2 on 2022-08-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0002_remove_ry_enquiry_header_cop_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_comments',
            name='Created_Date',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
