# Generated by Django 4.0.2 on 2022-07-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0003_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_comments',
            name='CreatedByUser',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_comments',
            name='LastUpdateby',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer_comments',
            name='LastUpdateddate',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
