# Generated by Django 3.2.13 on 2022-08-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0003_auto_20220802_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Distribution_Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=100, null=True)),
                ('GroupUsersID', models.CharField(max_length=500, null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'Email_Distribution_Groups',
            },
        ),
    ]
