# Generated by Django 4.0.2 on 2022-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0003_other_details_quantity_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
