# Generated by Django 4.0.4 on 2022-06-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0003_rename_usename_user_details_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_comments',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False)),
                ('CustomerName', models.TextField(max_length=200, null=True)),
                ('Comments', models.TextField(max_length=200, null=True)),
                ('Rno', models.TextField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'customer_comments',
                'ordering': ['Rno'],
            },
        ),
    ]
