# Generated by Django 4.0.2 on 2022-08-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0004_user_details_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
