# Generated by Django 4.0.4 on 2022-06-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0004_customer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_comments',
            name='Reply',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
