# Generated by Django 4.0.4 on 2022-06-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0005_customer_comments_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_comments',
            old_name='CustomerName',
            new_name='UserId',
        ),
        migrations.RemoveField(
            model_name='customer_comments',
            name='Reply',
        ),
    ]
