# Generated by Django 4.0.2 on 2022-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0005_rename_lastupdateby_customer_comments_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_comments',
            name='UserId',
        ),
        migrations.AddField(
            model_name='customer_comments',
            name='Commments_to',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_comments',
            name='CreatedByUser',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer_comments',
            name='Created_Date',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
