# Generated by Django 4.0.4 on 2022-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0006_rename_customername_customer_comments_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_comments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ry_enquiry_items',
            name='Id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
