# Generated by Django 4.0.2 on 2022-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0006_remove_customer_comments_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=10, null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
                ('Action', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'role_checking_details',
            },
        ),
    ]
