# Generated by Django 4.0.2 on 2022-07-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0007_rolecheck'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleCheck',
            new_name='User_Role_Action',
        ),
        migrations.AlterModelTable(
            name='user_role_action',
            table='User_Role_Action',
        ),
    ]
