# Generated by Django 4.0.4 on 2022-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0007_alter_customer_comments_id_alter_ry_enquiry_items_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_comments',
            options={'ordering': ['DT']},
        ),
        migrations.AddField(
            model_name='customer_comments',
            name='DT',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
