# Generated by Django 4.0.2 on 2022-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0008_rename_rolecheck_user_role_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Upload_file', models.FileField(max_length=300, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Upload_data',
            },
        ),
        migrations.AlterField(
            model_name='purchase',
            name='popdf',
            field=models.FileField(max_length=500, null=True, upload_to=''),
        ),
    ]
