# Generated by Django 4.0.2 on 2022-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0010_upload_data_date_upload_data_last_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_data',
            name='Last_Status',
        ),
        migrations.RemoveField(
            model_name='upload_data',
            name='Process',
        ),
        migrations.AddField(
            model_name='upload_data',
            name='Process_Status',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='upload_data',
            name='Upload_Status',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload_data',
            name='Upload_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
