# Generated by Django 4.0.2 on 2022-08-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RY_Enquiry_Form', '0011_remove_upload_data_last_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='Date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
